<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1588903869730" stop="1588903869855">
  <name>scripts</name>
  <labels/>
  <test-cases>
    <test-case start="1588903869730" status="failed" stop="1588903869848">
      <name>test_login.TestLogin.test_login_001</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;scripts.test_login.TestLogin object at 0x10d173278&gt;

    def test_login_001(self):
&gt;       assert 0
E       assert 0

scripts/test_login.py:4: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="608-MainThread"/>
        <label name="host" value="china.local"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1588903869852" status="passed" stop="1588903869853">
      <name>test_login.TestLogin.test_login_002</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="608-MainThread"/>
        <label name="host" value="china.local"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1588903869854" status="passed" stop="1588903869855">
      <name>test_login.TestLogin.test_login_003</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="608-MainThread"/>
        <label name="host" value="china.local"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
